import { User } from './user.model';

export const userList: User[] = [
  {
    id: 1,
    first_name: 'King',
    last_name: 'McCaughran',
    email: 'kmccaughran0@gov.uk',
    expiration_date: '1616717128000',
    salary: 2000,
    deletedUser: false,
  },
  {
    id: 2,
    first_name: 'Margaretha',
    last_name: 'Gallaher',
    email: 'mgallaher1@ucoz.ru',
    expiration_date: '1641204026000',
    salary: 2700,
    deletedUser: false,
  },
  {
    id: 3,
    first_name: 'Beitris',
    last_name: 'Chamberlin',
    email: 'bchamberlin2@google.ca',
    expiration_date: '1617902537000',
    salary: 2300,
    deletedUser: false,
  },
  {
    id: 4,
    first_name: 'Isadora',
    last_name: 'Beneteau',
    email: 'ibeneteau3@google.es',
    expiration_date: '1641082210000',
    salary: 3000,
    deletedUser: false,
  },
  {
    id: 5,
    first_name: 'Jill',
    last_name: 'Cecil',
    email: 'jcecil4@boston.com',
    expiration_date: '1620952941000',
    salary: 2500,
    deletedUser: false,
  },
  {
    id: 6,
    first_name: 'Rina',
    last_name: 'Mackiewicz',
    email: 'rmackiewicz5@de.vu',
    expiration_date: '1614199523000',
    salary: 3200,
    deletedUser: false,
  },
  {
    id: 7,
    first_name: 'Lemmie',
    last_name: 'Jaffra',
    email: 'ljaffra6@npr.org',
    expiration_date: '1624553256000',
    salary: 2800,
    deletedUser: false,
  },
  {
    id: 8,
    first_name: 'Rustie',
    last_name: 'Minmagh',
    email: 'rminmagh7@yahoo.com',
    expiration_date: '1612206483000',
    salary: 3500,
    deletedUser: false,
  },
  {
    id: 9,
    first_name: 'Somerset',
    last_name: 'McVee',
    email: 'smcvee8@nps.gov',
    expiration_date: '1614345098000',
    salary: 2100,
    deletedUser: false,
  },
  {
    id: 10,
    first_name: 'Vin',
    last_name: 'Fearnside',
    email: 'vfearnside9@tripod.com',
    expiration_date: '1637918861000',
    salary: 2200,
    deletedUser: false,
  },
];
